Development  ddeyc17
rgr182/Umbraco---DDEyC pull request #46
Opened 2024-06-06 18:01 UTC by Gapcroz

Add footer title to general Content Page

2024-06-06 21:54 UTC, Paroxyse approved these changes
LGTM

2024-06-07 17:51 UTC, rgr182 requested changes

2024-06-07 17:51 UTC, rgr182 commented on DD/Views/Partials/homePage/_footer.cshtml
> +    document.addEventListener('DOMContentLoaded', function () {
Esto es una mala practica please corrije tu implementacion para usar clases especificas para eso

2024-06-07 17:55 UTC, Gapcroz commented on DD/Views/Partials/homePage/_footer.cshtml
> +    document.addEventListener('DOMContentLoaded', function () {
ah cierto, está pasando lo de la otra vez, permíteme revisarlo y cambiarlo

2024-06-10 22:29 UTC, Paroxyse commented on DD/wwwroot/Styles/GeneralContentPage.css
don't commit files if there are only whitespace changes

2024-06-10 22:31 UTC, Paroxyse reviewed
Functional changes look fine, there are too many whitespace changes, please avoid doing that.
Will test before merging

2024-06-10 22:33 UTC, rgr182 commented
> Functional changes look fine, there are too many whitespace changes, please avoid doing that. Will test before merging

>it's sup to u dude

2024-06-11 00:39 UTC, merged