Development  ddeyc17
rgr182/Umbraco---DDEyC pull request #52
Opened 2024-06-13 00:14 UTC by Gapcroz

Increase the size of the image carousel.
Scale the maximum height in the carousel to accommodate different image heights.

2024-06-13 01:07 UTC, Paroxyse commented on DD/Views/Partials/blocklist/_socialMediaItems.cshtml
uhm, duplicate code

2024-06-13 01:07 UTC, Paroxyse requested changes
Remove duplicate code from socialMediaItems

2024-06-13 16:39 UTC, Gapcroz commented on DD/Views/Partials/blocklist/_socialMediaItems.cshtml
I already fixed that duplicated code

2024-06-13 18:01 UTC, Gapcroz commented
I've changed appsettings because of the new dynamic NavigationBar, there's no need to continue with this lines in appsettings:

  "Navigation":[
      "Emprendimiento",
      "Capacitacion",
      "Ferias y Eventos",
      "Sector Industrial",
      "Apoyos y Financiamientos"
    ]

2024-06-13 19:11 UTC, rgr182 requested changes

2024-06-13 19:11 UTC, rgr182 commented on DD/Views/Partials/homePage/_navigation.cshtml
> +    // M�todo para obtener los hijos visibles
Any Comment in English pls

2024-06-13 19:11 UTC, rgr182 commented on DD/Views/Partials/homePage/_navigation.cshtml
> +        var ddeycPage = visibleDescendants.FirstOrDefault(x => x.Name == "DDEYC");
No Magic Strings!

2024-06-17 19:25 UTC, Gapcroz commented
resolved conflict with 2 archives
appsettings.json
ContentCarousel.css

2024-06-17 19:30 UTC, Paroxyse requested changes
You deleted styles unrelated to your task in ContentCarousel.css, bring those back

2024-06-17 19:30 UTC, Paroxyse commented on DD/wwwroot/Styles/ContentCarousel.css
You deleted styles unrelated to your task, which are used elsewhere on the code and do not  interfere with your task, restore them

2024-06-17 19:30 UTC, Paroxyse commented on DD/wwwroot/Styles/ContentCarousel.css
> -    overflow: hidden;
this style shouldn't have been removed

2024-06-17 19:30 UTC, Paroxyse commented on DD/wwwroot/Styles/ContentCarousel.css
> -
this one also shouldn't have been removed

2024-06-17 19:30 UTC, Paroxyse commented on DD/wwwroot/Styles/ContentCarousel.css
>  }
Or this one

2024-06-17 19:30 UTC, Paroxyse commented on DD/wwwroot/Styles/ContentCarousel.css
> -    .col-8.mt-5.mb-5 {
I'm not sure if deleting this breaks anything, please check if it does

2024-06-17 19:32 UTC, Paroxyse commented on DD/wwwroot/Styles/ContentCarousel.css
> -    overflow: hidden;
this may cause issues due to the fact that deleting the .not-footer class and just leaving it as is now also affects the footer

2024-06-17 19:34 UTC, Paroxyse commented on DD/wwwroot/Styles/ContentCarousel.css
> -    }
I'm not sure if deleting this breaks anything, please check if it does

2024-06-17 20:32 UTC, merged