Dev ddcm 45
rgr182/Umbraco---DDEyC pull request #60
Opened 2024-08-07 19:07 UTC by Gapcroz

2024-08-07 20:13 UTC, Paroxyse commented on DD/DD.csproj
Remove google forms entries for csproj, they aren't used

2024-08-07 20:20 UTC, Paroxyse commented on DD/DD.sln
Should this be in version control? @rgr182

2024-08-07 20:23 UTC, Paroxyse commented on DD/Middleware/ViewAnalyticsMiddleware.cs
This shouldn't be in changed files I think, this file is already in stage

2024-08-07 20:25 UTC, Paroxyse commented on DD/Views/BackOffice/Analytics.cshtml
dead code

2024-08-07 20:26 UTC, Paroxyse commented on DD/Views/LandingPage.cshtml
don't commit whitespace

2024-08-07 20:27 UTC, Paroxyse commented on DD/Views/Partials/homePage/googleForm.cshtml
dead code

2024-08-07 20:30 UTC, Paroxyse commented on DD/models/ViewAnalytics.cs
this doesn't correspond to this pr, this file should already be in stage

2024-08-07 20:31 UTC, Paroxyse commented on DD/wwwroot/Scripts/googleForm.js
dead code

2024-08-07 20:32 UTC, Paroxyse requested changes
Remove dead code and sync pr with stage before merging

2024-08-07 20:53 UTC, Gapcroz commented on DD/Views/BackOffice/Analytics.cshtml
Erased file.

2024-08-07 20:55 UTC, Gapcroz commented on DD/Views/Partials/homePage/googleForm.cshtml
erased file.

2024-08-07 20:55 UTC, Gapcroz commented on DD/wwwroot/Scripts/googleForm.js
erased file.

2024-08-07 21:06 UTC, Gapcroz commented on DD/models/ViewAnalytics.cs
erased file.

2024-08-08 00:32 UTC, Paroxyse approved these changes

2024-08-08 00:37 UTC, merged